version: '3'

x-shared-environment: &shared-environment
  POSTGRES_DB: test_mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  DB_HOST: db_test
  DB_PORT: 5432

services:
  api_test:
    build:
      context: ./api
    ports:
      - "8080:8080" 
    environment:
      DB_HOST: db_test
      DB_PORT: 5432
      POSTGRES_DB: test_mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - db_test
      - init-db_test

  db_test:
    image: postgres:13
    environment:
      <<: *shared-environment
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data

  init-db_test:
    build:
      context: ./db
      dockerfile: Dockerfile-db-init
    environment:
      <<: *shared-environment
    depends_on:
      - db_test

  crawler_test:
    build:
      context: ./crawler
    environment:
      <<: *shared-environment
    depends_on:
      - db_test
      - init-db_test

  validator_test:
    build:
      context: ./validator
    environment:
      <<: *shared-environment
    depends_on:
      - db_test
      - init-db_test
      - crawler_test

  integration_api_test:
    build:
      context: ./api
    command: /bin/bash -c "pytest tests"
    depends_on:
      - api_test
      - init-db_test
      - crawler_test
      - validator_test
    environment:
      <<: *shared-environment
