version: '3'

x-shared-environment: &shared-environment
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  DB_HOST: db
  DB_PORT: 5432

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - db
      - init-db

  website:
    build:
      context: ./website
    ports:
      - "3000:3000"
  db:
    image: postgres:13
    environment:
      <<: *shared-environment
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  init-db:
    build:
      context: ./db
      dockerfile: Dockerfile-db-init
    environment:
      <<: *shared-environment
    depends_on:
      - db

  crawler:
    build:
      context: ./crawler
    environment:
      <<: *shared-environment
    depends_on:
      - db

volumes:
  db-data: