
CREATE TABLE official_satellites ( 
    official_name VARCHAR(255) PRIMARY KEY,
    reg_country VARCHAR(255),
    own_country VARCHAR(255),
    owner_name VARCHAR(255),
    user_type VARCHAR(255),
    purposes VARCHAR(255),
    orbit_class VARCHAR(16), 
    orbit_type VARCHAR(255),
    geo_longitude VARCHAR(255),
    perigee VARCHAR(255),
    apogee VARCHAR(255),
    eccentricity VARCHAR(255),
    inclination VARCHAR(255),
    period_min VARCHAR(255),
    mass_launch VARCHAR(255),
    mass_dry VARCHAR(255),
    power_watts VARCHAR(255),
    launch_date VARCHAR(255),
    exp_lifetime VARCHAR(255),
    contractor VARCHAR(255),
    contractor_country VARCHAR(255),
    launch_site VARCHAR(255),
    launch_vehicle VARCHAR(255),
    cospar_number  VARCHAR(20),
    norad_number integer,
    comment_note VARCHAR(255),
    source_orbit VARCHAR(255)
    );

COPY official_satellites(    
    official_name,
    reg_country,
    own_country,
    owner_name,
    user_type,
    purposes,
    orbit_class, 
    orbit_type,
    geo_longitude,
    perigee,
    apogee,
    eccentricity,
    inclination,
    period_min,
    mass_launch,
    mass_dry,
    power_watts,
    launch_date,
    exp_lifetime,
    contractor,
    contractor_country,
    launch_site,
    launch_vehicle,
    cospar_number,
    norad_number,
    comment_note,
    source_orbit
    ) 
FROM './UCS-Satellite-Database-Officialname-1-1-2023.csv' 
WITH (FORMAT CSV, DELIMITER ',', QUOTE '"');